import Kaji
import Dynamic

# Alo! Alo! Testing! Testing!
Zoo = Kaji.LList()
Zoo.inserts("Ape", 1)
Zoo.inserts("Rats", 2)
Zoo.inserts("Lion", 3)
Zoo.inserts("Porcupine", 4)
Zoo.inserts("Snake", 3)
Zoo.inserts("Tiger", 2)
Zoo.inserts("Tortoise", 1)
Zoo.inserts("Rhinoceros", 1)
Zoo.display()
Zoo.inserts("Fish", 2)
Zoo.display()
Zoo.deletes(4)
Zoo.display()
print(Zoo.searches("Rhinoceros"))
print(Zoo.searches("Bats"))
print(Zoo.searches("Rats"))
Zoo.inserts("Koala", 9)
Zoo.display()
print(Zoo.tail.data)
Zoo.deletes(9)
Zoo.display()
print(Zoo.tail.data)

# Alo! Alo! Testing! Testing!
Fruits = Dynamic.LIFO()
Fruits.pop()
Fruits.push("Pawpaw")
Fruits.push("Carrots")
Fruits.push("Pear")
Fruits.push("Strawberry")
Fruits.push("Orange")
Fruits.push("Banana")
Fruits.stk.display()
Fruits.pop()
Fruits.stk.display()
Fruits.pop()
Fruits.stk.display()
print(Fruits.pop())
Fruits.stk.display()
print(Fruits.top())
# Alo! Alo! Testing! Testing!
Fleur = Dynamic.FIFO()
Fleur.enqueue("Sunflower")
Fleur.enqueue("Roses")
Fleur.enqueue("Tulips")
Fleur.enqueue("Lily")
Fleur.que.display()
print(Fleur.dequeue())
print(Fleur.front())
Fleur.que.display()
Eagle = Kaji.Node()
Eagle.data = "Eagle"
Vulture = Kaji.Node()
Vulture.data = "Vulture"
Eagle.setNext(Vulture)
Fruits.stk.tail.setNext(Eagle)
Fruits.stk.display()
print("\n")
# Alo! Alo! Testing! Testing!
print(Fruits)
print(Zoo)
print(Fleur)
print(Eagle)
